export const notes = [
    {
      date: "14.08.2024",
      title: "Reminder",
      content: "Don't forget to implement a dark theme with those two colors saved into the Figma project file.",
      tags: [
        { name: "Reminder", color: "red" },
        { name: "Project", color: "blue" },
      ],
      project: "uuid-12345",
      importance: "very-high",
      task: "uuid-67890",
      list: "uuid-11111",
    },
    {
      date: "15.08.2024",
      title: "",
      content: "Research the latest trends in UX design for the planner project.",
      tags: [
        { name: "Project", color: "blue" },
        { name: "Personal", color: "green" },
      ],
      project: "uuid-22334",
      importance: "high",
      task: "uuid-44556",
      list: "uuid-78901",
    },
    {
      date: "16.08.2024",
      title: "Chore",
      content: "Buy groceries and prepare the meal plan for the week.",
      tags: [
        { name: "Chore", color: "yellow" },
        { name: "Personal", color: "green" },
      ],
      project: "",
      importance: "normal",
      task: "",
      list: "uuid-33333",
    },
    {
      date: "17.08.2024",
      title: "Personal Note",
      content: "Schedule a dentist appointment and check annual health insurance coverage.",
      tags: [
        { name: "Personal", color: "green" },
        { name: "Reminder", color: "red" },
      ],
      project: "",
      importance: "high",
      task: "uuid-55678",
      list: "",
    },
    {
      date: "18.08.2024",
      title: "",
      content: "Outline the main topics for the upcoming blog article on web development.",
      tags: [
        { name: "Project", color: "blue" },
        { name: "Reminder", color: "red" },
      ],
      project: "uuid-99887",
      importance: "normal",
      task: "",
      list: "",
    },
    {
      date: "19.08.2024",
      title: "Project Update",
      content: "Finalize the homepage layout and push it to the dev branch.",
      tags: [
        { name: "Project", color: "blue" },
        { name: "Reminder", color: "red" },
      ],
      project: "",
      importance: "very-high",
      task: "",
      list: "",
    },
    {
      date: "20.08.2024",
      title: "Task List",
      content: "Clean the house, organize bookshelves, and vacuum the living room.",
      tags: [
        { name: "Chore", color: "yellow" },
        { name: "Personal", color: "green" },
      ],
      project: "",
      importance: "low",
      task: "",
      list: "uuid-22222",
    },
    {
      date: "21.08.2024",
      title: "Random Thought",
      content: "Consider switching to a better hosting service for improved website performance.",
      tags: [
        { name: "Personal", color: "green" },
        { name: "Project", color: "blue" },
      ],
      project: "",
      importance: "very-low",
      task: "",
      list: "",
    },
    {
      date: "22.08.2024",
      title: "Planner Idea",
      content: "Include a feature for exporting tasks as PDFs.",
      tags: [
        { name: "Project", color: "blue" },
        { name: "Reminder", color: "red" },
      ],
      project: "uuid-11223",
      importance: "high",
      task: "",
      list: "uuid-45454",
    },
    {
      date: "23.08.2024",
      title: "Weekly Review",
      content: "Write a summary of achievements and lessons learned for this week.",
      tags: [
        { name: "Personal", color: "green" },
        { name: "Chore", color: "yellow" },
      ],
      project: "",
      importance: "normal",
      task: "",
      list: "uuid-55667",
    },
  ];
  
  